OpenSTLinux DTS test config
Yocto compilation error: /cpus/cpu@0: Reference to non-existent node or label "vddcore". 
This board is not using PMIC so need to define discrete power scheme in DTS.